export const ADDRESS_LIST = [
  { id: null, value: '선택' },
  { id: 0, value: '제주시' },
  { id: 1, value: '조천읍' },
  { id: 2, value: '구좌읍' },
  { id: 3, value: '성산읍' },
  { id: 4, value: '표선면' },
  { id: 5, value: '남원읍' },
  { id: 6, value: '서귀포시' },
  { id: 7, value: '안덕면' },
  { id: 8, value: '대정읍' },
  { id: 9, value: '한경읍' },
  { id: 10, value: '한림읍' },
  { id: 11, value: '애월읍' },
  { id: 12, value: '추자도' },
  { id: 13, value: '우도면' },
];
