import LayoutMain from '../layouts/LayoutMain';

export default function Home() {
  return (
    <LayoutMain>
      <div style={{ fontSize: '3rem' }}>
        pr 테스트! main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
        <br />
        main page
      </div>
    </LayoutMain>
  );
}
